import React from "react";

const sizeClasses = {
  txtQuicksandBold18: "font-bold font-quicksand",
  txtQuicksandBold16: "font-bold font-quicksand",
  txtQuicksandBold14: "font-bold font-quicksand",
  txtInterSemiBold22Bluegray900: "font-inter font-semibold",
  txtQuicksandBold12: "font-bold font-quicksand",
  txtInterSemiBold26: "font-inter font-semibold",
  txtInterSemiBold24: "font-inter font-semibold",
  txtQuicksandBold24WhiteA700: "font-bold font-quicksand",
  txtQuicksandSemiBold32: "font-quicksand font-semibold",
  txtQuicksandSemiBold30: "font-quicksand font-semibold",
  txtPoppinsMedium20Green500: "font-medium font-poppins",
  txtQuicksandBold18Gray90003: "font-bold font-quicksand",
  txtQuicksandSemiBold32Teal900: "font-quicksand font-semibold",
  txtInterBold62: "font-bold font-inter",
  txtQuicksandSemiBold30Teal900: "font-quicksand font-semibold",
  txtInterSemiBold30: "font-inter font-semibold",
  txtInterBold60: "font-bold font-inter",
  txtInterBold14Gray100: "font-bold font-inter",
  txtQuicksandBold18Teal9009f: "font-bold font-quicksand",
  txtQuicksandSemiBold28: "font-quicksand font-semibold",
  txtInterSemiBold22Cyan800: "font-inter font-semibold",
  txtQuicksandSemiBold24: "font-quicksand font-semibold",
  txtQuicksandSemiBold22: "font-quicksand font-semibold",
  txtQuicksandSemiBold14Gray90003: "font-quicksand font-semibold",
  txtQuicksandSemiBold20: "font-quicksand font-semibold",
  txtPoppinsMedium20Orange300: "font-medium font-poppins",
  txtQuicksandBold20Teal900: "font-bold font-quicksand",
  txtQuicksandSemiBold20WhiteA700: "font-quicksand font-semibold",
  txtInterMedium24WhiteA700: "font-inter font-medium",
  txtPoppinsSemiBold20: "font-poppins font-semibold",
  txtQuicksandSemiBold28Gray100: "font-quicksand font-semibold",
  txtQuicksandBold14Teal9009f: "font-bold font-quicksand",
  txtQuicksandBold24Teal900: "font-bold font-quicksand",
  txtQuicksandBold42Cyan800: "font-bold font-quicksand",
  txtQuicksandRegular18Gray90003: "font-normal font-quicksand",
  txtQuicksandSemiBold18: "font-quicksand font-semibold",
  txtQuicksandSemiBold10Cyan800: "font-quicksand font-semibold",
  txtInterMedium22WhiteA700: "font-inter font-medium",
  txtQuicksandSemiBold16: "font-quicksand font-semibold",
  txtQuicksandSemiBold14WhiteA700: "font-quicksand font-semibold",
  txtQuicksandSemiBold14: "font-quicksand font-semibold",
  txtQuicksandBold32: "font-bold font-quicksand",
  txtQuicksandSemiBold12: "font-quicksand font-semibold",
  txtQuicksandBold30: "font-bold font-quicksand",
  txtQuicksandSemiBold10: "font-quicksand font-semibold",
  txtPoppinsBold20Teal900: "font-bold font-poppins",
  txtQuicksandSemiBold20Black900: "font-quicksand font-semibold",
  txtQuicksandBold28WhiteA700: "font-bold font-quicksand",
  txtQuicksandBold24Black900: "font-bold font-quicksand",
  txtQuicksandMedium16Teal9009f: "font-medium font-quicksand",
  txtQuicksandMedium12WhiteA700: "font-medium font-quicksand",
  txtQuicksandBold24Orange300: "font-bold font-quicksand",
  txtQuicksandSemiBold16Black900: "font-quicksand font-semibold",
  txtQuicksandSemiBold28Teal900: "font-quicksand font-semibold",
  txtQuicksandSemiBold20Teal900: "font-quicksand font-semibold",
  txtQuicksandSemiBold24Teal900: "font-quicksand font-semibold",
  txtQuicksandMedium14WhiteA700: "font-medium font-quicksand",
  txtQuicksandBold28: "font-bold font-quicksand",
  txtQuicksandBold24: "font-bold font-quicksand",
  txtQuicksandMedium20WhiteA700: "font-medium font-quicksand",
  txtQuicksandBold22: "font-bold font-quicksand",
  txtQuicksandBold20: "font-bold font-quicksand",
  txtPoppinsBold20Orange300: "font-bold font-poppins",
  txtQuicksandMedium8Teal9009f: "font-medium font-quicksand",
  txtQuicksandBold22Orange300: "font-bold font-quicksand",
  txtQuicksandRegular20Black900: "font-normal font-quicksand",
  txtQuicksandMedium20WhiteA7009f: "font-medium font-quicksand",
  txtQuicksandSemiBold12Black900: "font-quicksand font-semibold",
  txtQuicksandBold16Teal900: "font-bold font-quicksand",
  txtQuicksandSemiBold24Black900: "font-quicksand font-semibold",
  txtInterSemiBold20Gray90005: "font-inter font-semibold",
  txtInterMedium26Gray700: "font-inter font-medium",
  txtQuicksandSemiBold20Cyan800: "font-quicksand font-semibold",
  txtInterMedium24: "font-inter font-medium",
  txtQuicksandRegular14: "font-normal font-quicksand",
  txtQuicksandRegular12: "font-normal font-quicksand",
  txtInterSemiBold22Gray700: "font-inter font-semibold",
  txtInterMedium22: "font-inter font-medium",
  txtQuicksandRegular10: "font-normal font-quicksand",
  txtQuicksandSemiBold30Black900: "font-quicksand font-semibold",
  txtInterMedium26: "font-inter font-medium",
  txtInterBold24: "font-bold font-inter",
  txtQuicksandRegular12Teal900: "font-normal font-quicksand",
  txtQuicksandSemiBold14Teal900: "font-quicksand font-semibold",
  txtQuicksandMedium18Cyan800: "font-medium font-quicksand",
  txtQuicksandSemiBold16Teal900: "font-quicksand font-semibold",
  txtInterBold20: "font-bold font-inter",
  txtQuicksandRegular12Black900: "font-normal font-quicksand",
  txtQuicksandSemiBold12Teal900: "font-quicksand font-semibold",
  txtQuicksandSemiBold18Teal900: "font-quicksand font-semibold",
  txtInterMedium24Gray700: "font-inter font-medium",
  txtQuicksandMedium18Teal9009f: "font-medium font-quicksand",
  txtQuicksandRegular18Teal900: "font-normal font-quicksand",
  txtQuicksandMedium12Teal9009f: "font-medium font-quicksand",
  txtInterBold14: "font-bold font-inter",
  txtQuicksandSemiBold18Cyan800: "font-quicksand font-semibold",
  txtQuicksandRegular24: "font-normal font-quicksand",
  txtQuicksandRegular16Teal9009f: "font-normal font-quicksand",
  txtQuicksandBold42: "font-bold font-quicksand",
  txtQuicksandMedium18Black900: "font-medium font-quicksand",
  txtQuicksandBold42Teal900: "font-bold font-quicksand",
  txtQuicksandMedium12Teal900: "font-medium font-quicksand",
  txtQuicksandRegular20: "font-normal font-quicksand",
  txtQuicksandMedium18Teal900: "font-medium font-quicksand",
  txtQuicksandSemiBold16Cyan800: "font-quicksand font-semibold",
  txtPoppinsMedium20: "font-medium font-poppins",
  txtQuicksandRegular18: "font-normal font-quicksand",
  txtQuicksandSemiBold16Cyan8009f: "font-quicksand font-semibold",
  txtQuicksandRegular16: "font-normal font-quicksand",
  txtQuicksandMedium14WhiteA7009f: "font-medium font-quicksand",
  txtQuicksandBold20Black900: "font-bold font-quicksand",
  txtQuicksandSemiBold18Black900: "font-quicksand font-semibold",
  txtQuicksandMedium20: "font-medium font-quicksand",
  txtInterSemiBold20Green300: "font-inter font-semibold",
  txtQuicksandRegular7: "font-normal font-quicksand",
  txtQuicksandMedium22: "font-medium font-quicksand",
  txtQuicksandMedium24: "font-medium font-quicksand",
  txtQuicksandSemiBold12Cyan800: "font-quicksand font-semibold",
  txtQuicksandMedium28: "font-medium font-quicksand",
  txtPoppinsMedium14: "font-medium font-poppins",
  txtQuicksandMedium8: "font-medium font-quicksand",
  txtQuicksandSemiBold1333: "font-quicksand font-semibold",
  txtQuicksandMedium10: "font-medium font-quicksand",
  txtQuicksandMedium12: "font-medium font-quicksand",
  txtQuicksandBold32Teal900: "font-bold font-quicksand",
  txtQuicksandMedium14: "font-medium font-quicksand",
  txtPoppinsBold20: "font-bold font-poppins",
  txtQuicksandMedium16: "font-medium font-quicksand",
  txtQuicksandSemiBold24WhiteA700: "font-quicksand font-semibold",
  txtQuicksandMedium18: "font-medium font-quicksand",
  txtQuicksandBold16Teal9009f: "font-bold font-quicksand",
  txtInterSemiBold26WhiteA700: "font-inter font-semibold",
  txtInterMedium24Lightgreen200: "font-inter font-medium",
  txtInterSemiBold22: "font-inter font-semibold",
  txtQuicksandMedium28Teal900: "font-medium font-quicksand",
  txtInterSemiBold20: "font-inter font-semibold",
  txtInterSemiBold26Black900: "font-inter font-semibold",
  txtQuicksandBold18Teal900: "font-bold font-quicksand",
  txtQuicksandBold14Teal900: "font-bold font-quicksand",
  txtQuicksandBold28Orange300: "font-bold font-quicksand",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
